routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'Main\IndexController@index')->name('home');
Route::get('/{href}', 'Main\IndexController@show')->name('show');

Route::prefix('/user')->group(function (){
    Route::get('login','User\AuthController@login')->name('user_login');
    Route::get('register','User\AuthController@register')->name('user_register');
    Route::post('signin','User\AuthController@signin')->name('user_signin');
    Route::post('signup','User\AuthController@signup')->name('user_signup');
    Route::get('logout','User\AuthController@logout')->name('user_logout');
});

Route::prefix('/admin')->name('admin.')->group(function (){
    Route::get('login','Admin\AuthController@login')->name('login');
    Route::post('signin','Admin\AuthController@signin')->name('signin');
    Route::middleware('admin_middle')->group(function (){
        Route::get('dashboard', 'Admin\AdminController@index')->name('dashboard');
        Route::get('logout','Admin\AuthController@logout')->name('logout');
        Route::post('update','Admin\AdminController@update')->name('user_update');
        Route::resource('products', 'Admin\ProductsController');
    });
});

Auth::routes();

resources/views/admin/dashboard.blade.php
@extends('layouts.admin')

@section('title') Панель управления @endsection

@section('content')
    <div class="card-body create_body">
        @if ($errors->any())
            <ul class="alert alert-danger list_type_none">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        @endif

        {!! Form::open(['url' => '/admin/update', 'class' => 'form-horizontal']) !!}
            <div class="form-group {{ $errors->has('email') ? 'has-error' : ''}}">
                {!! Form::label('email', 'Эл. почта ', ['class' => 'control-label']) !!}
                {!! Form::text('email', Auth::user()->email, ['class' => 'form-control']) !!}
            </div>
            <div class="form-group {{ $errors->has('new_password') ? 'has-error' : ''}}">
                {!! Form::label('new_password', 'Новый пароль', ['class' => 'control-label']) !!}
                <input id="new_password" type="password" name="new_password" class="form-control new_password">
            </div>
            <div class="form-group old_password @if(session()->get('wrong',null)===true) old_password_wrong has-error @endif">
                {!! Form::label('current_password', 'Текущий пароль', ['class' => 'control-label']) !!}
                <input id="current_password" type="password" name="current_password" class="form-control">
            </div>
            <div class="form-group text-right">
                {!! Form::submit('Обновить', ['class' => 'btn btn-success']) !!}
            </div>
        {!! Form::close() !!}
    </div>
@endsection

@section('script')
    <script>
        $(function () {
            $(".new_password").keyup(function () {
                let current = $(this).val();
                if (current){
                    $('.old_password').slideDown();
                } else{
                    $('.old_password').slideUp();
                }
            })
        })
    </script>
@endsection

resources/views/admin/login.blade.php
@extends('layouts.auth')

@section('auth_title') Логин @endsection

@section('form')
    <form method="post" action="{{ route('admin.signin') }}">
        @csrf
        <div class="card card-login card-hidden">
            <div class="card-header text-center">
                <h4 class="card-title">Логин</h4>
            </div>
            <div class="card-content">
                @if(session()->has('invalid_admin'))
                    <h5 class="c-red text-center">Неправильный email или пароль</h5>
                @endif
                <div class="input-group">
                    <span class="input-group-addon">
                        <i class="material-icons">face</i>
                    </span>
                    <div class="form-group label-floating">
                        <label class="control-label">Эл. почта</label>
                        <input name="email" type="text" class="form-control" value="{{ old('email') }}">
                    </div>
                </div>
                <div class="input-group">
                    <span class="input-group-addon">
                        <i class="material-icons">lock_outline</i>
                    </span>
                    <div class="form-group label-floating">
                        <label class="control-label">Пароль</label>
                        <input name="password" type="password" class="form-control">
                    </div>
                </div>
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-wd btn-lg btn-success">Войти</button>
            </div>
        </div>
    </form>
@endsection