routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'Main\IndexController@index')->name('home');
Route::get('/{href}', 'Main\IndexController@show')->name('show');

Route::prefix('/user')->group(function (){
    Route::get('login','User\AuthController@login')->name('user_login');
    Route::get('register','User\AuthController@register')->name('user_register');
    Route::post('signin','User\AuthController@signin')->name('user_signin');
    Route::post('signup','User\AuthController@signup')->name('user_signup');
    Route::get('logout','User\AuthController@logout')->name('user_logout');
});

Route::prefix('/admin')->name('admin.')->group(function (){
    Route::get('login','Admin\AuthController@login')->name('login');
    Route::post('signin','Admin\AuthController@signin')->name('signin');
    Route::middleware('admin_middle')->group(function (){
        Route::get('dashboard', 'Admin\AdminController@index')->name('dashboard');
        Route::get('logout','Admin\AuthController@logout')->name('logout');
        Route::post('update','Admin\AdminController@update')->name('user_update');
        Route::resource('products', 'Admin\ProductsController');
    });
});

Auth::routes();

resources/views/layouts/admin.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Dashboard</title>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons" />
    <link rel="apple-touch-icon" sizes="76x76" href="http://www.urbanui.com/" />
    <link href="{{ asset('dashboard/assets/css/bootstrap.min.css') }}" rel="stylesheet" />
    <link href="{{ asset('dashboard/assets/css/turbo.css') }}" rel="stylesheet" />
    <link href="{{ asset('dashboard/assets/css/fileinput.css') }}">
    <link href="{{ asset('dashboard/assets/css/demo.css') }}" rel="stylesheet" />
    <link href="{{ asset('dashboard/editor/codemirror.min.css') }}" rel="stylesheet">
    <link href="{{ asset('dashboard/editor/froala_editor.pkgd.min.css') }}" rel="stylesheet">
    <link href="{{ asset('dashboard/editor/froala_style.min.css') }}" rel="stylesheet">
    <link href="{{ asset('dashboard/editor/codemirror5.css') }}" rel="stylesheet">
    <link href="{{ asset('dashboard/multiselect/select.css') }}" rel="stylesheet"/>
    <link href="{{ asset('dashboard/css/main.css') }}" rel="stylesheet">
    @yield('style')
</head>

<body>
<div class="wrapper">
    <div class="sidebar">
        <div class="sidebar-wrapper">
            <ul class="nav">
                <li>
                    <a href="{{ route('admin.dashboard') }}" class="@if($route == 'admin/dashboard') active_page @endif">
                        <i class="material-icons">dashboard</i>
                        <p>Панель управления</p>
                    </a>
                </li>
                <li>
                    <a href="{{ route('admin.products.index') }}" class="@if($route == 'admin/products') active_page @endif">
                        <i class="fa fa-list-alt "></i>
                        <p>Товары </p>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="main-panel">
        <nav class="navbar navbar-default navbar-absolute" data-topbar-color="blue">
            <div class="container-fluid">
                <div class="navbar-minimize">
                    <button id="minimizeSidebar" class="btn btn-round btn-white btn-fill btn-just-icon">
                        <i class="material-icons visible-on-sidebar-regular f-26">keyboard_arrow_left</i>
                        <i class="material-icons visible-on-sidebar-mini f-26">keyboard_arrow_right</i>
                    </button>
                </div>
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse languages">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="" class="logout">
                                <i class="fa fa-sign-out"></i>
                            </a>
                        </li>
                        <li class="separator hidden-lg hidden-md"></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            @yield('content')
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>

<script src="{{ asset('dashboard/assets/vendors/jquery-3.1.1.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('dashboard/assets/vendors/jquery-ui.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('dashboard/assets/vendors/bootstrap.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('dashboard/assets/vendors/material.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('dashboard/assets/vendors/perfect-scrollbar.jquery.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('dashboard/assets/vendors/jquery.validate.min.js') }}"></script>
<script src="{{ asset('dashboard/assets/vendors/moment.min.js') }}"></script>
<script src="{{ asset('dashboard/assets/vendors/chartist.min.js') }}"></script>
<script src="{{ asset('dashboard/assets/vendors/jquery.bootstrap-wizard.js') }}"></script>
<script src="{{ asset('dashboard/assets/vendors/bootstrap-notify.js') }}"></script>
<script src="{{ asset('dashboard/assets/vendors/bootstrap-datetimepicker.js') }}"></script>
<script src="{{ asset('dashboard/assets/vendors/jquery-jvectormap.js') }}"></script>
<script src="{{ asset('dashboard/assets/vendors/nouislider.min.js') }}"></script>
<script src="{{ asset('dashboard/assets/vendors/jquery.select-bootstrap.js') }}"></script>
<script src="{{ asset('dashboard/assets/vendors/jquery.datatables.js') }}"></script>
<script src="{{ asset('dashboard/assets/vendors/sweetalert2.js') }}"></script>
<script src="{{ asset('dashboard/assets/vendors/jasny-bootstrap.min.js') }}"></script>
<script src="{{ asset('dashboard/assets/vendors/fullcalendar.min.js') }}"></script>
<script src="{{ asset('dashboard/assets/vendors/jquery.tagsinput.js') }}"></script>
<script src="{{ asset('dashboard/assets/js/turbo.js') }}"></script>
<script src="{{ asset('dashboard/assets/js/fileinput.js') }}"></script>
<script src="{{ asset('dashboard/assets/js/demo.js') }}"></script>
<script src="{{ asset('dashboard/editor/codemirror.min.js') }}"></script>
<script src="{{ asset('dashboard/editor/codemirror5.js') }}"></script>
<script src="{{ asset('dashboard/editor/froala_editor.pkgd.min.js') }}"></script>
<script src="{{ asset('dashboard/js/main.js') }}"></script>
<script>
    $(function () {
        @if(session()->has('added'))
            swal({
                type:'success',
                title:'Добавлен!',
                showConfirmButton:false,
                timer:2000
            }).catch(swal.loop);
        @endif
        @if(session()->has('updated'))
            swal({
                type:'success',
                title:'Обновлен!',
                showConfirmButton:false,
                timer:2000
            }).catch(swal.loop);
        @endif
        @if(session()->has('deleted'))
            swal({
                type:'success',
                title:'Удалён!',
                showConfirmButton:false,
                timer:2000
            }).catch(swal.loop);
        @endif
    });
</script>
@yield('script')
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/auth.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="http://www.urbanui.com/" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>@yield('auth_title')</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <link href="{{ asset('dashboard/assets/css/bootstrap.min.css') }}" rel="stylesheet" />
    <link href="{{ asset('dashboard/assets/css/turbo.css') }}" rel="stylesheet" />
    <link href="{{ asset('dashboard/assets/css/demo.css') }}" rel="stylesheet" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons" />
</head>
<body>

<a href="{{ route('home') }}">
    <i class="fa fa-home back_to_home"></i>
</a>
<nav class="navbar navbar-primary navbar-transparent navbar-absolute">
    <div class="container">
        <div class="navbar-header">
        </div>
    </div>
</nav>
<div class="wrapper wrapper-full-page">
    <div class="full-page login-page"  data-color="blue">
        <div class="content">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 col-sm-6 col-md-offset-4 col-sm-offset-3">
                        @yield('form')
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>

<script src="{{ asset('dashboard/assets/vendors/jquery-3.1.1.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('dashboard/assets/vendors/jquery-ui.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('dashboard/assets/vendors/bootstrap.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('dashboard/assets/vendors/material.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('dashboard/assets/vendors/perfect-scrollbar.jquery.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('dashboard/assets/vendors/jquery.validate.min.js') }}"></script>
<script src="{{ asset('dashboard/assets/vendors/moment.min.js') }}"></script>
<script src="{{ asset('dashboard/assets/vendors/chartist.min.js') }}"></script>
<script src="{{ asset('dashboard/assets/vendors/jquery.bootstrap-wizard.js') }}"></script>
<script src="{{ asset('dashboard/assets/vendors/bootstrap-notify.js') }}"></script>
<script src="{{ asset('dashboard/assets/vendors/bootstrap-datetimepicker.js') }}"></script>
<script src="{{ asset('dashboard/assets/vendors/jquery-jvectormap.js') }}"></script>
<script src="{{ asset('dashboard/assets/vendors/nouislider.min.js') }}"></script>
<script src="{{ asset('dashboard/assets/vendors/jquery.select-bootstrap.js') }}"></script>
<script src="{{ asset('dashboard/assets/vendors/jquery.datatables.js') }}"></script>
<script src="{{ asset('dashboard/assets/vendors/sweetalert2.js') }}"></script>
<script src="{{ asset('dashboard/assets/vendors/jasny-bootstrap.min.js') }}"></script>
<script src="{{ asset('dashboard/assets/vendors/fullcalendar.min.js') }}"></script>
<script src="{{ asset('dashboard/assets/vendors/jquery.tagsinput.js') }}"></script>
<script src="{{ asset('dashboard/assets/js/turbo.js') }}"></script>
<script src="{{ asset('dashboard/assets/js/demo.js') }}"></script>

<script type="text/javascript">
    $().ready(function() {
        demo.checkFullPageBackgroundImage();
        setTimeout(function() {
            $('.card').removeClass('card-hidden');
        }, 700)
    });
</script>
</html>

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@yield('title')</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
</head>
<body>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <nav class="navbar navbar-expand-sm bg-light">
                <ul class="navbar-nav d-flex justify-content-between" style="width:100%">
                    <div>
                        <li class="nav-item">
                            <a class="nav-link" href="/">Главная</a>
                        </li>
                    </div>
                    @auth
                        <div class="d-flex">
                            <li class="nav-item">
                                <a class="nav-link" href="#">Добро пожаловать {{ Auth::user()->name }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('user_logout') }}">Выйти</a>
                            </li>
                        </div>
                    @else
                        <div class="d-flex">
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('user_login') }}">Логин</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('user_register') }}">Регистрация</a>
                            </li>
                        </div>
                    @endauth
                </ul>
            </nav>
            @yield('content')
        </div>
    </div>
</div>

<script src="/main/js/jquery.min.js"></script>
<script src="/main/js/bootstrap.min.js"></script>
<script src="/main/js/main.js"></script>

</body>
</html>